Hw14
baldezhnik/HomeWorkTMS pull request #1
Opened 2022-04-23 23:39 UTC by baldezhnik

тут и 14 и 15 дз

2022-04-24 14:34 UTC, OKurcheuskaya commented
разные домашки должны быть в разных ветках

2022-04-24 14:47 UTC, OKurcheuskaya requested changes

2022-04-24 14:47 UTC, OKurcheuskaya commented on app/src/main/java/com/dsd/homework/MainActivity.kt
> +
не оставляй пустые строки

2022-04-24 14:47 UTC, OKurcheuskaya commented on app/src/main/java/com/dsd/homework/MainActivity.kt
> +            1-> {button2.text = hw14.zagadkaList[i].getOtvet()
попробуй убрать дублирование кода, путем создания метода

2022-04-24 14:47 UTC, OKurcheuskaya commented on app/src/main/java/com/dsd/homework/MainActivity.kt
> +        val activity = Intent(this, HW14Activity::class.java)
наименование переменных должны быть говорящими. не activity a  intent

2022-04-24 22:04 UTC, baldezhnik commented
> разные домашки должны быть в разных ветках

из-за того что у меня создан класс User и ListUser которые используются в 2-ух домашках, то мне бы пришлось в двух ветках его создавать, или ждать пока вы бы одобрили 14 домашку, потом соединять, кре каша.
последующие домашки постараюсь в разных ветках)

2022-04-25 05:46 UTC, OKurcheuskaya approved these changes

2022-04-25 07:09 UTC, merged