Hw20
baldezhnik/HomeWorkTMS pull request #6
Opened 2022-05-26 19:28 UTC by baldezhnik

Там во вью модели передается и строковый и собственный класс, можно было бы к одному преобразовать, но пусть останется так для меня

2022-05-30 13:34 UTC, OKurcheuskaya requested changes

2022-05-30 13:34 UTC, OKurcheuskaya commented on app/src/main/java/com/dsd/homework/hw18/HW18Activity.kt
> +        val tv_act18_vegetable: TextView = findViewById(R.id.tv_act18_vegetable)
переменные должны быть в одном стиле. у тебя viewModel и tv_act18_vegetable

2022-05-31 13:48 UTC, baldezhnik commented on app/src/main/java/com/dsd/homework/hw18/HW18Activity.kt
> +        val tv_act18_vegetable: TextView = findViewById(R.id.tv_act18_vegetable)
Я принял замечание, но исправлять тут уже не буду, т.к. в 21 домашке, я все переделал во фрагменты, и там уже используется другой viewModel, сгенерированный студией, и названия переменных уже от viewBindning. Прошу просто засчитать. т.к. не вижу смысла в слиянии этой ветки с мастером.

2022-06-06 08:00 UTC, OKurcheuskaya approved these changes

2022-06-06 09:19 UTC, merged